server:
  port: 8004
  # 服务名
spring:
  application:
    name: service-cms
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.25.223.229:3306/online_edu?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 120.25.223.229:8848
  #redis 配置
  redis:
    host: 120.25.223.229
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
mybatis-plus:
  configuration:
    #mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #配置mapper xml文件的路径
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zgz.cmsservice.pojo




